---
version: 1

build_arg_defaults:
  # ANSIBLE_GALAXY_CLI_COLLECTION_OPTS:
  # ANSIBLE_GALAXY_CLI_ROLE_OPTS:
  EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.12-latest
  EE_BUILDER_IMAGE: quay.io/ansible/ansible-builder:latest

# NOTE: the ansible-builder command must be running within this directory for these relative paths to resolve correctly
ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append: |
    RUN echo This is a post-install command!
    RUN ls -la /etc
