---
- name: Test EE collections
  hosts: localhost
  gather_facts: true

  collections:
    - kubernetes.core

  tasks:
    - name: Use module from awx.awx collection
      awx.awx.host:
        name: dummy
        inventory: dummy
      ignore_errors: true

    - name: Use module from kubernetes.core collection
      k8s:
        name: dummy
      ignore_errors: true
