---
name: api

on:
  push:
  workflow_dispatch:

jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Hit up the API
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          id
          sudo add-apt-repository ppa:savoury1/curl34 -y
          sudo apt update
          sudo apt install curl -y
          curl --request GET \
          --url "https://api.github.com/repos/jrgoldfinemiddleton/dummy1" \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: Bearer $GITHUB_TOKEN" \
          --fail-with-body
