---
on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl --request GET \
          --url "https://api.github.com/repos/jrgoldfinemiddleton/dummy1" \
          --header "Accept: application/vnd.github.v3+json" \
          --header "Authorization: Bearer $GITHUB_TOKEN }}"
