---
name: Lint
on:
  - push
  - workflow_dispatch
jobs:
  Lint-Yaml:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Python libraries
        run: pip install -r requirements.txt

      - name: Run yamllint
        run: yamllint .
