---
name: Validate PR

on:  # yamllint disable-line rule:truthy
  pull_request:

jobs:
  validate-conventional-commits:
    runs-on: ubuntu-22.04
    steps:
      - name: Validate PR title
        uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint-yaml:
    runs-on: ubuntu-22.04
    needs: validate-conventional-commits
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip

      - name: Upgrade pip
        run: pip install --upgrade pip setuptools wheel

      - name: Install Python libraries
        run: pip install -r requirements.txt

      - name: Run yamllint
        run: yamllint --strict .
